### ISSUE TITLE
Error while creating the room

### ISSUE THREAD

**Issue by thealoneprogrammer** [meething/openhouse#6]
I was just going through the project, really great work. But when I try to run the same locally it works fine sometimes and in some cases, i get the following error while creating the room

room.js:507 Uncaught TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at Gun.<anonymous> (room.js:507)
    at Object.val (gun.js:1837)
    at gun.js:1831

This leads other participants to be unable to join the room. Can I get any help regarding the same?

**Comment by lmangani** [comment]
Hello @thealoneprogrammer and thanks for giving this a try!
This looks like a GUN related issue possibly based on the error position, no peers are discovered. Hard to tell why.

I'm not actually maintaining this demo, but would suggest trying this evolution instead: https://github.com/meething/webrtctzn (there are p2p, janus SFU, and GUN audio timeline modes)
If you get the same issues, then its most definitely a network related challenge.

**Comment by thealoneprogrammer** [comment]
@lmangani Thank you for the quick reply 😁. I would definitely love to try out the alternate.

**Comment by lmangani** [comment]
@thealoneprogrammer no problem! looking forward to your feedback! feel free to post any updates here if needed, we can still work out this issue if you plan on using any of this demo
